### ISSUE TITLE
Release 10.0.0

### ISSUE THREAD

**Issue by benjaminkott** [TYPO3GmbH/blog#130]
# TODO

## Blog Integration and Standalone ✔

The blog setup is currently too hard. We need to improve here to make it easy for everyone to set up a blog quickly and start blogging. To make it easy, the blog needs to provide two different modes. 

- Expert
- Standalone
- Integration

The **standalone** mode should provide a full page template and should become the new default for blog setups.

The **integration** mode should make it as easy as possible to be integrated into existing websites that are following the best practices for typo3 templating.

- #125

## Blog Setup  ✔

The current setup lacks to provide samples of essential features and needs to be enhanced.
It needs to make use of the new planned standalone mode.  ✔

## Page Module ✔

Should show information about the blog post that is stored in the page.

- #135 ✔

## Backend Modules ✔

The backend module currently makes it hard to browse between different blogs within a TYPO3 site.
The problem here is that it only shows the storage folder and misses the site context/path completely.

- #107 ✔

**Comment by medarob** [comment]
Here are some things I was struggling with when I integrated the blog extension the first time in TYPO3 7.6 in our website:

**- RSS Feed**
This should be available without any Typoscript configuration. An on/off toogle for each blog (if there are several) with all blog posts including the author in the article(!). Currently the author of the post is not in the RSS feed and you have to change the template for that (because we changed it). There is also no documention on the RSS feature as far as I can see in the docu. A search for RSS has no results.

Path to RSS feed: I integrated the RSS feed into the sidebar (which is available on every blog page) and this caused a problem. Now there were different links to the RSS feed depending on which page I visit. If I'm in the listview I have a link like `/blog/blog-feed.rss`, inside an article I have `/blog/article/blog-feed.rss`. Not sure if that is good or bad (maybe bad because of dublicate content?) or if it is possible to configure the path for each domain so that the path in the sidebar for the rss feed stays the same?

**- documentation and step by step tutorials**
When I first integrated the blog in our website there were little tutorials/examples. A blog example extension was available (and is still available) but it's difficult to look at the code and try to adapt the things to your own blog. When something is not working you don't know why, ...what's missing?
Therefore the documention could be expanded.
List **all features** with images and how they look in the frontend in the documention without the need to install the blog example extension.

**- How to set up more than 1 blog on a website?**
Again: documentation. This is not really explained anywhere. I read that it should be possible but I haven't found any example. For example a website has different departments and every department wants to have an own blog.
Can an author be part of two or more blogs? For example aI have two or more blogs on my website and 1 author can publish articles for all or only 2 blogs (if the total blog count is 3). What is the best practise to configure such a scenario? It would be good to have only one folder per author where he puts all his articles. So should the author give the articles a certain blog category to make them available in different blogs?

There are many questions and best practises missing. Maybe it's all plausible for advanced users but it's not so easy for beginners. That is why examples are good but they need explanations. "Why do I need certain things to configure to make it work?" For example I followed the instruction step by step (that was in TYPO3 7.6) and it did not work as expected - and then the time consuming part began... (I had to adapt the template and I still don't know why some things in the template are not working as in the example extension)

**Comment by cogtail** [comment]
Here are my four suggestions:

- Images inside RSS-Feed: As you can see in feed readers like Feedly, there are no images in the RSS feed. We should create a solution for this; currently works: <enclosure url="{f:uri.image(src: post.media.0.uid, treatIdAsReference: '1', absolute: '1')}" length="{post.media.0.originalResource.size}" type="image/jpeg"/> Or for the new version: <enclosure url="{f:uri.page(pageUid: '1', absolute: '1')}{post.featuredImage.originalResource.publicUrl}" length="{post.featuredImage.originalResource.size}" type="image/jpeg"/>

- Images inside search results: I think images inside a search like ke_search (and maybe indexed_search) would be very helpful.

- Managing blog posts exclusively through the list module: It would be great if we managed the blog posts exclusively through the list module. We have the great "Hide child pages in page tree" feature. Now all you need is a button called "Display blog post" next to "Edit record" and "View webpage". "Display (or Edit) blog post" could be a link in the list module to the page view.

- More flexibility for “Display blog post header”: There are layouts in which post image and headline are separated. Maybe you can either split this element into "image" and "headline" (and maybe "date") or add a configuration option (display only image / display only headline).

**Comment by SchoolGuy** [comment]
Just a quick question about this issue: When is there a planned release for Typo3 10LTS? For me this is quite of a showstopper. I tried to use the current version in V10 and didn't encounter issues I would see on the frontend. Is there anything I can help with to progress this possibly?

**Comment by cogtail** [comment]
Yes, that's pretty frustrating. Current compatibility problems with Fluid 3.0 are not sufficient reasons for me. Unfortunately we don't know anything about a planned release. There is no feedback. Apparently there is nothing we can do but wait.

**Comment by dev-rke** [comment]
@benjaminkott What exactly is missing to release the current master branch as a new stable version? 
May we help to finish it?

It feels a bit strange planning a production release containing a dev-master dependency. ;-)

**Comment by christian-fries** [comment]
What can we do to help you releasing a TYPO3 10 compatible version?

**Comment by Tuurlijk** [comment]
Sponsoring perhaps? If so, what method do you prefer?
