### ISSUE TITLE
User can't edit subtitle of Blog Post

### ISSUE THREAD

**Issue by JeroenVeghel** [TYPO3GmbH/blog#217]
# Support

**Is your question related to a problem? Please describe.**

When i'm logged in as an Admin i can edit the subtitle of a Blog Post.
When i edit the Blog Post as a user, i don't see the subtitle field.
Is this related to access rights? If so, where can I activate it, since I can't seem to find it.

**Comment by helsner** [comment]
The subtitle field is a core field, not related to the blog post AFAIK.
So in case its missing, it might be caused by your overall setup.
The field can be allowed in the exclude fields in your access rights.
https://docs.typo3.org/m/typo3/tutorial-getting-started/master/en-us/UserManagement/GroupPermissions/Index.html#allowed-exclude-fields
For the record page

**Comment by JeroenVeghel** [comment]
Ah found it, thank you very much!
